
$("document").ready(function(){
    $("#answer-btn1").on("click",function(){
        $(".answer1").fadeToggle();
    });
    $("#answer-btn2").on("click",function(){
        $(".answer2").fadeToggle();
    });
    $("#answer-btn3").on("click",function(){
        $(".answer3").fadeToggle();
    });
    $("#answer-btn4").on("click",function(){
        $(".answer4").fadeToggle();
    });
    $("#answer-btn5").on("click",function(){
        $(".answer5").fadeToggle();
    });
    $("#answer-btn6").on("click",function(){
        $(".answer6").fadeToggle();
    });
    $("#answer-btn7").on("click",function(){
        $(".answer7").fadeToggle();
    });
    $("#answer-btn8").on("click",function(){
        $(".answer8").fadeToggle();
    });
    $("#answer-btn9").on("click",function(){
        $(".answer9").fadeToggle();
    });
    $("#answer-btn10").on("click",function(){
        $(".answer10").fadeToggle();
    });
    $("#answer-btn11").on("click",function(){
        $(".answer11").fadeToggle();
    });
    $("#answer-btn12").on("click",function(){
        $(".answer12").fadeToggle();
    });
    $("#answer-btn13").on("click",function(){
        $(".answer13").fadeToggle();
    });
    $("#answer-btn14").on("click",function(){
        $(".answer14").fadeToggle();
    });
    $("#answer-btn15").on("click",function(){
        $(".answer15").fadeToggle();
    });
    $("#answer-btn16").on("click",function(){
        $(".answer16").fadeToggle();
    });
});